/*
 * File: app/view/mainContainer.js
 * Date: Tue Oct 18 2011 12:33:50 GMT-0700 (PDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define("MyApp.view.mainContainer", {
  extend: 'MyApp.view.ui.mainContainer',

  initialize: function() {
    var me = this;
    me.callParent(arguments);
  },

  login: function(button, e, options) {
    button.up('#tabPanel1').setActiveItem(1);
    button.up('#tabPanel1').down('#tabPanel1Sub').setActiveItem(0);
  },

  logout: function(button, e, options) {
    button.up('#tabPanel1').setActiveItem(0);
        
    ssss;s
  },

  addExpense: function(button, e, options) {
    button.up('#tabPanel1Sub').setActiveItem(1);
  },

  onAddExpense: function(button, e, options) {
    var message = {
      'merchant': button.up('#formPanelAdd').down('#merchant').getValue(),
      'category': button.up('#formPanelAdd').down('#category').getValue(),
      'amount': button.up('#formPanelAdd').down('#amount').getValue()
    };
    Ext.io.send('queue/expense', message);
    Ext.getCmp('expenseList').getStore().add(message);
    button.up('#tabPanel1Sub').setActiveItem(0);
  },

  onExpenseListActivate: function(component, options) {
    Ext.define('Expense',  {extend: "Ext.data.Model",
      fields: [
      {name: 'merchant', type: 'string'},
      {name: 'category', type: 'string'},
      {name: 'amount',   type: 'int'}
      ],
      proxy: {
        id: 'expenseProxy',
        type: 'syncstorage',
        key: 'expense'
      }
    });
    Ext.io.setup({key: "expense"});
    Ext.io.init();
            
    Ext.getCmp('expenseList').setStore(Ext.create('Ext.data.Store',{
      model: 'Expense',
    }));
    Ext.io.subscribe('queue/expense',function(from,message){  // JCM this should be from a config option
      message.me= false;
      var record = Ext.create('Expense',message);
      Ext.getCmp('expenseList').getStore().add(record); // JCM then add()?
    },this);
  },

  onButtonRelease: function(button, e, options) {

  }

});