/*
 * File: app/view/ui/mainContainer.js
 * Date: Tue Oct 18 2011 12:33:50 GMT-0700 (PDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.mainContainer', {
  extend: 'Ext.Container',

  config: {
    layout: {
      type: 'fit'
    }
  },

  initialize: function() {
    var me = this;
    me.setItems([
      {
        xtype: 'container',
        id: 'tabPanel1',
        layout: {
          type: 'card'
        },
        items: [
          {
            xtype: 'formpanel',
            itemId: 'formPanelLogin',
            layout: {
              pack: 'center',
              type: 'vbox'
            },
            items: [
              {
                xtype: 'fieldset',
                items: [
                  {
                    xtype: 'textfield',
                    id: 'username',
                    label: {
                      width: 96,
                      text: 'Username '
                    }
                  },
                  {
                    xtype: 'passwordfield',
                    id: 'password',
                    label: {
                      width: '34%',
                      text: 'Password'
                    }
                  }
                ]
              },
              {
                xtype: 'button',
                ui: 'confirm',
                text: 'Login',
                listeners: [
                  {
                    event: 'tap',
                    scope: me,
                    fn: me.login
                  }
                ]
              }
            ]
          },
          {
            xtype: 'container',
            itemId: 'expenseListContainer',
            ui: 'light',
            layout: {
              type: 'fit'
            },
            items: [
              {
                xtype: 'toolbar',
                style: 'font-size: .8em;',
                title: 'Welcome Aditya',
                docked: 'top',
                layout: {
                  pack: 'end',
                  type: 'hbox'
                },
                items: [
                  {
                    xtype: 'button',
                    ui: 'confirm',
                    text: 'Logout',
                    listeners: [
                      {
                        event: 'tap',
                        scope: me,
                        fn: me.logout
                      },
                      {
                        event: 'release',
                        scope: me,
                        fn: me.onButtonRelease
                      }
                    ]
                  }
                ]
              },
              {
                xtype: 'container',
                id: 'tabPanel1Sub',
                layout: {
                  type: 'card'
                },
                activeItem: 1,
                items: [
                  {
                    xtype: 'formpanel',
                    itemId: 'formPanelList',
                    layout: {
                      type: 'vbox'
                    },
                    items: [
                      {
                        xtype: 'list',
                        id: 'expenseList',
                        itemTpl: Ext.create('Ext.XTemplate', 
                          '<div>Merchant {merchant} on {date} Amount {amount}</div>'
                        ),
                        flex: 3,
                        listeners: [
                          {
                            event: 'activate',
                            scope: me,
                            fn: me.onExpenseListActivate
                          }
                        ]
                      },
                      {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        layout: {
                          align: 'center',
                          pack: 'center',
                          type: 'hbox'
                        },
                        items: [
                          {
                            xtype: 'button',
                            ui: 'confirm',
                            width: 173,
                            text: 'Add Expense',
                            listeners: [
                              {
                                event: 'tap',
                                scope: me,
                                fn: me.addExpense
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  },
                  {
                    xtype: 'formpanel',
                    itemId: 'formPanelAdd',
                    layout: {
                      align: 'center',
                      pack: 'center',
                      type: 'vbox'
                    },
                    items: [
                      {
                        xtype: 'fieldset',
                        items: [
                          {
                            xtype: 'textfield',
                            itemId: 'merchant',
                            label: 'Merchant'
                          },
                          {
                            xtype: 'selectfield',
                            itemId: 'category',
                            options: [
                              {
                                text: 'Banking',
                                value: 'banking'
                              },
                              {
                                text: 'Utilities',
                                value: 'utilities'
                              },
                              {
                                text: 'Cable',
                                value: 'cable'
                              }
                            ],
                            label: 'Category'
                          },
                          {
                            xtype: 'numberfield',
                            itemId: 'amount',
                            label: 'Amount'
                          }
                        ]
                      },
                      {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        layout: {
                          pack: 'center',
                          type: 'hbox'
                        },
                        items: [
                          {
                            xtype: 'button',
                            ui: 'confirm',
                            width: 173,
                            text: 'Save',
                            listeners: [
                              {
                                event: 'tap',
                                scope: me,
                                fn: me.onAddExpense
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        xtype: 'toolbar',
        height: 40,
        width: 320,
        title: 'Sencha Expenses',
        docked: 'top'
      }
    ]);
    me.callParent(arguments);
  },

  login: function(button, e, options) {
    
  },

  logout: function(button, e, options) {
    
  },

  onButtonRelease: function(button, e, options) {
    
  },

  onExpenseListActivate: function(component, options) {
    
  },

  addExpense: function(button, e, options) {
    
  },

  onAddExpense: function(button, e, options) {
    
  }

});