/*
 * File: designer.js
 * Date: Tue Oct 18 2011 12:33:50 GMT-0700 (PDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
  enabled: true
});

Ext.application({
  name: 'MyApp',

  launch: function() {
    var cmp1 = Ext.Viewport.add(Ext.create('MyApp.view.mainContainer', {}));
  }
});
